app/views/layouts/application.html.erb

yagishuhei

---

app/assets/stylesheets/customers.scss
app/controllers/customers_controller.rb
app/helpers/customers_helper.rb
app/views/customers/edit.html.erb
app/views/customers/show.html.erb
config/routes.rb
test/controllers/customers_controller_test.rb

Add controller customers

---

app/assets/stylesheets/addresses.scss
app/controllers/addresses_controller.rb
app/helpers/addresses_helper.rb
app/views/addresses/edit.html.erb
app/views/addresses/index.html.erb
test/controllers/addresses_controller_test.rb

start controller addresses

---

app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
test/controllers/items_controller_test.rb

[Start]first commit

---

app/models/address.rb
app/models/item.rb
db/migrate/20220517015127_create_items.rb
db/migrate/20220517015532_create_addresses.rb
test/fixtures/addresses.yml
test/fixtures/items.yml
test/models/address_test.rb
test/models/item_test.rb

Add model item and address

---

app/models/cart_item.rb
app/models/genre.rb
db/migrate/20220517014858_create_cart_items.rb
db/migrate/20220517015315_create_genres.rb
test/fixtures/cart_items.yml
test/fixtures/genres.yml
test/models/cart_item_test.rb
test/models/genre_test.rb

Add modelx2

---

app/controllers/admin/items_controller.rb
app/views/admin/items/new.html.erb

アドミンの新規商品ページとコントローラの記述を変更しました。

add admin_items_new_view

---

app/models/item.rb
config/environments/development.rb
db/migrate/20220517083841_create_active_storage_tables.active_storage.rb
db/schema.rb

ActiveStorage_install

---

config/environments/development.rb

fix confing

---

app/javascript/packs/application.js
app/javascript/stylesheets/application.scss
app/views/admin/items/new.html.erb
config/environments/development.rb
config/webpack/development.js
config/webpack/environment.js
package.json
yarn.lock

FontAwesome、Bootstrapをインストールしました。
アドミンのnewページの最後の</div>が抜けていた為、追記しました。

add Bootstrap FontAwesome

---

config/environments/development.rb

[Finish]fix_config

---

app/controllers/admin/items_controller.rb
app/views/admin/items/edit.html.erb

＃＃＃第一回＃＃＃
コントローラのupdate、editに記述をしました。
admin/items/editに記述をしました

addadmin_item_edit

---

app/controllers/admin/genres_controller.rb
app/views/admin/genres/index.html.erb

コントローラの編集
・edit action以外の記載全て
ビューの編集
・genre index view の記載全て

admin_genres_index

---

app/controllers/admin/orders_controller.rb
app/controllers/admin/sessions_controller.rb
app/views/admin/orders/top.html.erb
app/views/admin/sessions/new.html.erb
config/routes.rb

fix Log_in

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/top.html.erb
config/routes.rb

add orders_index

---

app/controllers/admin/sessions_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/sessions/new.html.erb

fix admin_session

---

app/controllers/public/orders_controller.rb
app/models/address.rb
app/views/public/orders/new.html.erb

注文入力画面を作成しました。
しかし登録ボタンを押しても画面遷移は出来ていません。

[Finish]public/order/new

---

app/controllers/public/customers_controller.rb
app/views/public/customers/show.html.erb

会員側のマイページを作成しました。管理者側の会員詳細ページと似たような箇所があるので部分テンプレートにできるかもしれませんが、作成していません。
idがないため動作確認は出来ておりません。

[Add]public/customer/show

---

app/controllers/public/registrations_controller.rb
app/views/admin/items/new.html.erb
app/views/public/registrations/new.html.erb
app/views/public/shared/_links.html.erb

会員の新規登録ページの作成をしました。
登録ができてないが、プッシュしました。
アイテムの新規登録もエラー出るが、プッシュしました。

customers sign_in

---

app/controllers/public/addresses_controller.rb
app/views/public/addresses/index.html.erb

配送先の登録・一覧画面を作成しました。
address controller, addresses/index.html.erb のファイルに記述しました。
新規登録の機能ですがrouting error が出ており修正は出来ていません。

[Fix]public/address/index layout

---

app/controllers/admin/items_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/genres/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/public/addresses/index.html.erb

Fix action

---

app/controllers/public/registrations_controller.rb
app/controllers/public/sessions_controller.rb
app/views/public/customers/show.html.erb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb
app/views/public/shared/_links.html.erb

ログイン・新規登録機能の修正をしました。
会員のShowページの修正をしました。

Public registrations

---

app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/genres/index.html.erb
app/views/admin/items/index.html.erb

ganre一覧のレイアウトを整えました。
編集ページへ遷移。新規投稿フォーム動作確認済です。

[Fix]layout

---

app/views/admin/genres/index.html.erb

[Fix]indent

---

app/views/layouts/_admin_header.html.erb
app/views/layouts/_gest_header.html.erb
app/views/layouts/_public_header.html.erb
app/views/layouts/application.html.erb

サインインユーザーの違いによるheaderの遷移を記載しました

[Update]header

---

app/views/layouts/application.html.erb
config/routes.rb

thirdcommit

---

app/controllers/public/sessions_controller.rb

fix log out

---

app/views/public/items/index.html.erb

imageのget_imageメソッドを変更しました。
加えて、会員側のitemレイアウトを変更しました。

Fix item image

---

app/controllers/public/addresses_controller.rb
app/views/public/addresses/index.html.erb

[Fix]address/index_actionの追記

---

app/controllers/public/addresses_controller.rb
app/views/public/addresses/edit.html.erb
app/views/public/addresses/index.html.erb

address controllerの記述を追加しました。
public/address/edit のビューページの記述をしました。

fix_address_edit

---

app/controllers/public/addresses_controller.rb

controllerにdestroyアクションを追記しました。

[Add]destroy_action

---

app/controllers/public/cart_items_controller.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/index.html.erb
config/routes.rb

fix cart_item_index

---

app/assets/stylesheets/public/searches.scss
app/controllers/public/searches_controller.rb
app/helpers/public/searches_helper.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/public/addresses/index.html.erb
app/views/public/customers/show.html.erb
app/views/public/items/_index.html.erb
app/views/public/orders/new.html.erb
app/views/public/searches/_form.html.erb
app/views/public/searches/search.html.erb
config/routes.rb
test/controllers/public/searches_controller_test.rb

検索機能をつけました。
商品名で検索することができ、部分一致の方法でコードを記入しました。

[Add]search-function

---

Gemfile
Gemfile.lock
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/orders_controller.rb
app/views/admin/customers/index.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/items/index.html.erb
app/views/admin/orders/index.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb

[Add]Adminのpage

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/items_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb
db/migrate/20220523050426_rename_count_column_to_cart_items.rb
db/schema.rb

カートアイテムのコントローラの記述の変更、itemモデルのアソシエーションを追記しました。
indexページの表示はできるようになりました。
indexページの<%#= cart_item.item.amount %>部分でエラーが出るためコメントアウトしてあります。
また、コントローラのdestroyとdestroy_allアクションでエラーが出てます。
updateアクションはまだ確認できていません。
createアクションで同じ商品が重複してます。
各アクションの修正はまだしてません！

fix cart_items_controller

---

app/controllers/public/cart_items_controller.rb

fix cart_items_controlles

---

app/controllers/public/cart_items_controller.rb
app/views/public/items/show.html.erb

fix cart_items

---

app/controllers/public/cart_items_controller.rb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb

カート機能の各アクションのエラーを修正しました。
レイアウトはまだ何もしてないです。

Cart items create

---

app/controllers/admin/items_controller.rb
app/controllers/public/cart_items_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/show.html.erb

[Fix]admin/index_error

---

app/controllers/admin/sessions_controller.rb

アドミンのサインアウト後のパスを変更しました
・admin/sessions_controller.rb

[Fix]admin_after_logout

---

app/controllers/public/orders_controller.rb
app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb
config/application.rb

オーダーのshowページでエラーが出てます。
コメントアウトしてる所全部エラーが出てます。

Orders show

---

app/views/admin/orders/show.html.erb

Fix,order/show

---

app/views/admin/orders/show.html.erb

[Fix]status表示

---

app/views/public/orders/show.html.erb

fix orders_show2

---

app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb

レイアウト整えました
・admin_index
・admin_edit

Layout admin genres

---

app/views/admin/genres/index.html.erb

[Fix]layout_index_center

---

app/controllers/public/orders_controller.rb
app/views/public/orders/show.html.erb

fix public_order

---

app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb

[Fix]小計の計算

---

app/controllers/public/orders_controller.rb
app/views/public/orders/order_confirm.html.erb
app/views/public/orders/show.html.erb

fix_orders_show

---

app/controllers/public/cart_items_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/genres/index.html.erb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/orders/order_confirm.html.erb
config/initializers/kaminari_config.rb

Fix amount

---

app/assets/stylesheets/public/genres.scss
app/controllers/public/genres_controller.rb
app/helpers/public/genres_helper.rb
app/views/public/genres/_index.html.erb
app/views/public/genres/show.html.erb
app/views/public/items/show.html.erb
config/routes.rb
test/controllers/public/genres_controller_test.rb

ジャンル一覧機能を作りました。
勝手に部分テンプレート化しておりますので、あしからず。

[Add]genre/index

---

app/controllers/public/items_controller.rb
app/views/admin/items/index.html.erb
app/views/homes/top.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

fix_layout_public/top

---

app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb
db/migrate/20220525060643_change_data_orders_to_order_status.rb
db/schema.rb

ステータスの日本語化と注文履歴一覧ページの支払い金額を送料込みにしました。
ステータスのデフォルトを入金待ちにしました。

fix_order_status

---

app/views/public/orders/show.html.erb

ordes_show_fix_view

---

app/controllers/public/addresses_controller.rb
app/controllers/public/customers_controller.rb
app/views/public/items/show.html.erb

addressの記述を修正、会員のストロングパラメータに修正をしました。

fix_customer_address

---

app/views/public/orders/index.html.erb

注文の注文詳細に関して、買った商品の名前をeachで繰り返し処理を行いました。

[Fix]order.order_detail.item.name

---

app/views/public/orders/new.html.erb

lastcommit

---

app/views/public/cart_items/index.html.erb

カート内に商品がない時の条件分岐を変更しました。また、レイアウトの調整をしました。

order_index_fix_2

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/lists.html.erb
app/views/admin/customers/show.html.erb
config/routes.rb

[Add]customer_lists

---

app/assets/stylesheets/application.css
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb

画面の右横の空白を修正、会員の新規登録とログインのレイアウトを修正しました。

public_sessions_view

---

app/assets/stylesheets/application.css
app/views/admin/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/public/sessions/new.html.erb

add background-image

---

app/assets/stylesheets/application.css
app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
app/views/admin/orders/show.html.erb
app/views/homes/top.html.erb
app/views/public/genres/show.html.erb
app/views/public/items/_index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/order_confirm.html.erb

Fix items view
